### ISSUE TITLE
Does not implement neopixel part of the Pimoroni API

### ISSUE THREAD

**Issue by sirockin** [RogerHardiman/node-pan-tilt-hat#2]
The Pimoroni API includes methods for setting the neopixel driver on the Pan/Tilt hat. This library does not yet implement those features.

**Comment by RogerHardiman** [comment]
Hot had time to test it (and I had not wired up the NeoPixels to my Pi) but the code looks fine so happy to merge.

Many thanks for the submission.

Roger

**Comment by sirockin** [comment]
Hi Roger

 

You’re welcome - thanks for creating the library in the first place.

 

I’ve only tested on my own pi with a GRB NeoPixel device but it works well with that.

 

Dave Sirockin
